ersion: 2

sources:
  - name: pizza_runner
    database: postgres
    schema: pizza_runner
    tables:
      - name: pizza_names
      - name: runners
      - name: pizza_toppings
      - name: runner_ratings
